# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
# See circleci rest api: https://circleci.com/docs/api/v2/index.html
version: 2.1

orbs:
  # The Node.js orb contains a set of prepackaged CircleCI configuration you can utilize
  # Orbs reduce the amount of configuration required for common tasks.
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@5.0.2

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build-and-publish-to-pages:
    # These next lines define a docker executor: https://circleci.com/docs/2.0/executor-types/
    # You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # A list of available CircleCI docker Convenience Images are available here: https://circleci.com/developer/images/image/cimg/node
    machine:
      image: ubuntu-2004:current
    resource_class: medium
    environment:
      CLOUDFLARE_ACCOUNT_ID: << pipeline.parameters.cloudflare_account_id >>
      CLOUDFLARE_API_TOKEN: << pipeline.parameters.cloudflare_api_token >>
      NAME: << pipeline.parameters.name >>
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - run: node --version
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: List of current files/folders before building project
          command: ls -laF
      - run:
          name: Build the project
          command: yarn pages:build
      - run:
          name: List of files after building project
          command: ls -laF
      - run:
          name: Deploy to cloudflare pages and workers
          command: CLOUDFLARE_ACCOUNT_ID=$CLOUDFLARE_ACCOUNT_ID CLOUDFLARE_API_TOKEN=$CLOUDFLARE_API_TOKEN yarn pages:publish --project-name=$NAME

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  sample:
    jobs:
      - build-and-publish-to-pages
